import Image from "next/image";
import { signInAction, signUpAction } from "@/app/actions/auth";
import { isSupabaseConfigured } from "@/lib/supabase/config";

export default async function LoginPage({ searchParams }: { searchParams: Promise<{ error?: string; message?: string }> }) {
  const params = await searchParams;
  const configured = isSupabaseConfigured();
  return <main className="grid min-h-screen place-items-center bg-mist px-4 py-10"><div className="w-full max-w-md rounded-3xl border border-brand-100 bg-white p-7 shadow-soft"><div className="flex items-center gap-4"><Image src="/metaslim-mark.jpg" alt="MetaSlim AI" width={56} height={56} className="size-14 rounded-2xl object-cover object-top"/><div><h1 className="text-xl font-bold text-ink">MetaSlim AI</h1><p className="text-sm text-slate-500">Malaysia Facebook Slimming Intelligence</p></div></div><div className="my-6 h-px bg-slate-100"/>{!configured && <p className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Supabase 尚未配置。请先在服务器环境变量设置 URL 与 Anon Key；本页不会收集或储存 Secret。</p>}{params.error && <p className="mb-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{params.error}</p>}{params.message && <p className="mb-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{params.message}</p>}<form className="space-y-4"><label className="block"><span className="label">Email</span><input name="email" type="email" required className="field" autoComplete="email"/></label><label className="block"><span className="label">Password</span><input name="password" type="password" minLength={8} required className="field" autoComplete="current-password"/></label><div className="grid grid-cols-2 gap-3"><button formAction={signInAction} disabled={!configured} className="primary-button">登录</button><button formAction={signUpAction} disabled={!configured} className="secondary-button">建立账号</button></div></form><p className="mt-5 text-xs leading-5 text-slate-500">认证由 Supabase Auth 处理。密码不会写入应用数据库、localStorage 或日志。</p></div></main>;
}
